from pathlib import Path
import argparse
import json
import math
import shutil
from datetime import datetime

from common import (
    central_atom_number,
    fail,
    honeycomb_patch,
    load_config,
    read_gro,
    read_itp_atoms,
    read_itp_bonds,
    read_moleculetype,
    roughness_values,
    unwrap_molecule,
    write_gro,
    write_index,
    write_wall_itp,
    write_wall_topology,
)

ROOT = Path(__file__).resolve().parents[1]
WALLS = ["GBOT", "GTOP", "GXMN", "GXMX", "GYMN", "GYMX"]


def wall_shape_lock_settings(cfg: dict) -> dict:
    settings = cfg.get("wall_shape_lock", {})
    if not settings.get("enabled", True):
        settings = dict(settings)
        settings["enabled"] = False
    return settings


def write_posre_itp(path: Path, atom_count: int, kx: float, ky: float, kz: float) -> None:
    lines = [
        "[ position_restraints ]",
        "; atom  funct      fcx          fcy          fcz",
    ]
    for atom_index in range(1, atom_count + 1):
        lines.append(f"{atom_index:7d}     1 {kx:12.3f} {ky:12.3f} {kz:12.3f}")
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def append_posre_includes(itp_path: Path, wall_name: str) -> None:
    text = itp_path.read_text(encoding="ascii")
    include_lines = ["", "; --- fixed-footprint rough-piston restraints, generated by patch v12 ---"]
    if wall_name == "GTOP":
        include_lines += [
            "#ifdef POSRES_GTOP_FULL",
            '#include "GTOP_posre_full.itp"',
            "#endif",
            "#ifdef POSRES_GTOP_PULL",
            '#include "GTOP_posre_pull.itp"',
            "#endif",
        ]
    else:
        include_lines += [
            "#ifdef POSRES_FIXED_WALLS",
            f'#include "{wall_name}_posre_fixed.itp"',
            "#endif",
        ]
    itp_path.write_text(text.rstrip() + "\n" + "\n".join(include_lines) + "\n", encoding="ascii")


def write_wall_shape_lock_files(initial_dir: Path, wall_name: str, atom_count: int, cfg: dict) -> None:
    settings = wall_shape_lock_settings(cfg)
    if not settings.get("enabled", True):
        return
    fixed_k = float(settings.get("fixed_wall_posres_k_kj_mol_nm2", 2000000.0))
    gtop_full_k = float(settings.get("gtop_nvt_posres_k_kj_mol_nm2", 3000000.0))
    gtop_xy_k = float(settings.get("gtop_pull_xy_posres_k_kj_mol_nm2", 3000000.0))
    gtop_z_k = float(settings.get("gtop_pull_z_shape_k_kj_mol_nm2", 0.0))
    if wall_name == "GTOP":
        write_posre_itp(initial_dir / "GTOP_posre_full.itp", atom_count, gtop_full_k, gtop_full_k, gtop_full_k)
        write_posre_itp(initial_dir / "GTOP_posre_pull.itp", atom_count, gtop_xy_k, gtop_xy_k, gtop_z_k)
    else:
        write_posre_itp(initial_dir / f"{wall_name}_posre_fixed.itp", atom_count, fixed_k, fixed_k, fixed_k)
    append_posre_includes(initial_dir / f"{wall_name}.itp", wall_name)


def gtop_extra_shape_bonds(coords, bonds, cfg):
    settings = cfg.get("gtop_rigidity", {})
    if not settings.get("enabled", False):
        return []
    cutoff = float(settings.get("extra_shape_bond_xy_cutoff_nm", 0.50))
    min_xy = float(settings.get("extra_shape_bond_min_xy_nm", 0.17))
    max_per_atom = int(settings.get("max_extra_shape_bonds_per_atom", 14))
    k_shape = float(settings.get("extra_shape_bond_k_kj_mol_nm2", 2000000.0))
    if cutoff <= 0 or max_per_atom <= 0 or k_shape <= 0:
        return []

    original = {tuple(sorted((int(i), int(j)))) for i, j in bonds}
    cell = cutoff
    buckets = {}
    for i, (x, y, _z) in enumerate(coords):
        key = (int(math.floor(x / cell)), int(math.floor(y / cell)))
        buckets.setdefault(key, []).append(i)

    candidates = []
    for key, indices in buckets.items():
        kx, ky = key
        neighbor_ids = []
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                neighbor_ids.extend(buckets.get((kx + dx, ky + dy), []))
        for i in indices:
            xi, yi, zi = coords[i]
            for j in neighbor_ids:
                if j <= i:
                    continue
                pair = tuple(sorted((i, j)))
                if pair in original:
                    continue
                xj, yj, zj = coords[j]
                dxy = math.hypot(xj - xi, yj - yi)
                if dxy < min_xy or dxy > cutoff:
                    continue
                d3 = math.sqrt((xj - xi) ** 2 + (yj - yi) ** 2 + (zj - zi) ** 2)
                candidates.append((dxy, d3, i, j))

    candidates.sort()
    counts = [0] * len(coords)
    extra = []
    for _dxy, d3, i, j in candidates:
        if counts[i] >= max_per_atom or counts[j] >= max_per_atom:
            continue
        counts[i] += 1
        counts[j] += 1
        extra.append((i, j, d3, k_shape))
    return extra


def inject_gtop_extra_shape_bonds(itp_path: Path, coords, bonds, cfg) -> int:
    extra = gtop_extra_shape_bonds(coords, bonds, cfg)
    if not extra:
        return 0
    lines = itp_path.read_text(encoding="ascii").splitlines()
    angle_index = None
    for idx, line in enumerate(lines):
        if line.strip().lower().startswith("[ angles"):
            angle_index = idx
            break
    if angle_index is None:
        fail(f"Cannot insert GTOP extra shape bonds: [ angles ] section not found in {itp_path}")
    block = [
        "",
        "; --- Patch v12: strong extra GTOP shape-lock springs for rigid rough pressure piston ---",
        "; ai aj funct r0 k",
    ]
    for i, j, d3, k_shape in extra:
        block.append(f"{i+1:7d} {j+1:7d} 1 {d3:.6f} {k_shape:.3f}")
    lines = lines[:angle_index] + block + lines[angle_index:]
    itp_path.write_text("\n".join(lines) + "\n", encoding="ascii")
    return len(extra)


def backup_or_remove_existing_cases(cases_root: Path, cfg: dict) -> None:
    existing = sorted(old for old in cases_root.glob("RMS_*") if old.is_dir())
    if not existing:
        return
    if bool(cfg.get("backup_existing_graphene_cases", True)):
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_root = cases_root.parent / f"02_GRAPHENE_CASES_BACKUP_{stamp}"
        backup_root.mkdir(parents=True, exist_ok=False)
        for old in existing:
            shutil.move(str(old), str(backup_root / old.name))
        print(f"Existing RMS_* cases were backed up to: {backup_root}")
    else:
        for old in existing:
            shutil.rmtree(old)


def backup_or_remove_selected_cases(cases_root: Path, selected_case_names: list[str], cfg: dict) -> None:
    """Remove or back up only the selected cases.

    This is used when adding RMS_0p000 after RMS_0p300/0p600/0p900 have
    already been generated or simulated.  It avoids touching existing roughness
    cases.
    """
    existing = [cases_root / name for name in selected_case_names if (cases_root / name).is_dir()]
    if not existing:
        return
    if bool(cfg.get("backup_existing_graphene_cases", True)):
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_root = cases_root.parent / f"02_GRAPHENE_CASES_SELECTED_BACKUP_{stamp}"
        backup_root.mkdir(parents=True, exist_ok=False)
        for old in existing:
            shutil.move(str(old), str(backup_root / old.name))
        print(f"Existing selected cases were backed up to: {backup_root}")
    else:
        for old in existing:
            shutil.rmtree(old)


def parse_rms_list(text: str) -> list[float]:
    out = []
    for part in text.replace(';', ',').split(','):
        part = part.strip()
        if not part:
            continue
        if part.upper().startswith('RMS_'):
            part = part[4:].replace('p', '.')
        out.append(float(part))
    if not out:
        raise ValueError('empty rms list')
    return out


def case_name(rms: float) -> str:
    return "RMS_" + f"{rms:.3f}".replace(".", "p")


def map_bottom(points, x0, y0, z0):
    return [(x0 + u, y0 + v, z0) for u, v in points]


def map_xwall(points, x, y0, z0):
    return [(x, y0 + u, z0 + v) for u, v in points]


def map_ywall(points, y, x0, z0):
    return [(x0 + u, y, z0 + v) for u, v in points]


def molecule_center(coords):
    return [sum(c[i] for c in coords) / len(coords) for i in range(3)]


def wrap_com_molecule(coords, box):
    com = molecule_center(coords)
    shift = []
    for axis in range(3):
        if box[axis] <= 0:
            shift.append(0.0)
        else:
            shift.append(-math.floor(com[axis] / box[axis]) * box[axis])
    shifted = [[c[0] + shift[0], c[1] + shift[1], c[2] + shift[2]] for c in coords]
    return shifted


def build_periodic_standard_kerogen(centered_molecules, source_box, cfg):
    """Tile the densified periodic kerogen bulk into a fixed rectangular slab.

    The old build used the raw atom extents of the bulk snapshot.  That can leave a
    lopsided cluster after visualisation and pressing.  Patch v12 instead fixes the
    target x/y footprint first, tiles the dense bulk periodically, then keeps whole
    molecules by COM inside the target slab.  This keeps all RMS cases with exactly
    the same lateral mold size and nearly the same initial thickness.
    """
    sp = cfg.get("standard_kerogen_plate", {})
    if not sp.get("enabled", True):
        return centered_molecules, None

    Lx = float(sp.get("plate_length_x_nm", source_box[0]))
    Ly = float(sp.get("plate_width_y_nm", source_box[1]))
    T = float(sp.get("initial_kerogen_thickness_nm", min(source_box[2], 6.0)))
    x0 = float(sp.get("origin_x_nm", cfg.get("outer_periodic_margin_nm", 2.0)))
    y0 = float(sp.get("origin_y_nm", cfg.get("outer_periodic_margin_nm", 2.0)))
    bottom_wall_z = float(sp.get("bottom_wall_z_nm", cfg.get("outer_periodic_margin_nm", 2.0)))
    bottom_gap = float(sp.get("bottom_wall_to_kerogen_gap_nm", cfg.get("wall_clearance_nm", 0.45)))
    z_min = bottom_wall_z + bottom_gap
    z_max = z_min + T
    com_margin = float(sp.get("whole_molecule_com_margin_nm", 0.25))
    max_mol = int(sp.get("max_selected_molecules", 1000000))

    # Prepare molecule templates whose COMs are inside the original periodic box.
    templates = []
    for mol in centered_molecules:
        coords = [(a["x"], a["y"], a["z"]) for a in mol]
        wrapped = wrap_com_molecule(coords, source_box)
        com = molecule_center(wrapped)
        rel_atoms = []
        for atom, c in zip(mol, wrapped):
            rel_atoms.append({
                "name": atom["name"],
                "dx": c[0] - com[0],
                "dy": c[1] - com[1],
                "dz": c[2] - com[2],
            })
        templates.append({"com": com, "atoms": rel_atoms})

    # Enough periodic images to cover the fixed target slab.
    nx0 = -1
    ny0 = -1
    nz0 = -1
    nx1 = int(math.ceil((Lx + 2 * source_box[0]) / source_box[0])) + 2
    ny1 = int(math.ceil((Ly + 2 * source_box[1]) / source_box[1])) + 2
    nz1 = int(math.ceil((T + 2 * source_box[2]) / source_box[2])) + 2

    candidates = []
    for ix in range(nx0, nx1 + 1):
        for iy in range(ny0, ny1 + 1):
            for iz in range(nz0, nz1 + 1):
                shift = (x0 + ix * source_box[0], y0 + iy * source_box[1], z_min + iz * source_box[2])
                for template_index, item in enumerate(templates):
                    cx = item["com"][0] + shift[0]
                    cy = item["com"][1] + shift[1]
                    cz = item["com"][2] + shift[2]
                    if not (x0 + com_margin <= cx <= x0 + Lx - com_margin):
                        continue
                    if not (y0 + com_margin <= cy <= y0 + Ly - com_margin):
                        continue
                    if not (z_min + com_margin <= cz <= z_max - com_margin):
                        continue
                    if bool(sp.get("reject_molecule_if_any_atom_outside_mold", True)):
                        atom_margin = float(sp.get("atom_boundary_margin_nm", 0.03))
                        outside = False
                        for rel in item["atoms"]:
                            ax = cx + rel["dx"]
                            ay = cy + rel["dy"]
                            az = cz + rel["dz"]
                            if ax < x0 + atom_margin or ax > x0 + Lx - atom_margin:
                                outside = True
                                break
                            if ay < y0 + atom_margin or ay > y0 + Ly - atom_margin:
                                outside = True
                                break
                            if az < z_min + atom_margin or az > z_max - atom_margin:
                                outside = True
                                break
                        if outside:
                            continue
                    # Prefer molecules with COM well inside the mold to avoid edge leakage.
                    edge = min(cx - x0, x0 + Lx - cx, cy - y0, y0 + Ly - cy, cz - z_min, z_max - cz)
                    candidates.append((edge, template_index, cx, cy, cz, item["atoms"]))

    if not candidates:
        fail("standard_kerogen_plate selected zero molecules. Increase initial_kerogen_thickness_nm or check bulk source.")

    # Keep all candidates by default, or limit by centrality if requested.
    candidates.sort(reverse=True, key=lambda row: row[0])
    candidates = candidates[:max_mol]
    # Restore deterministic order by z/y/x for reproducible molecule numbering.
    candidates.sort(key=lambda row: (row[4], row[3], row[2], row[1]))

    molecules = []
    for _edge, _idx, cx, cy, cz, rel_atoms in candidates:
        atoms = []
        for atom in rel_atoms:
            atoms.append({
                "name": atom["name"],
                "x": cx + atom["dx"],
                "y": cy + atom["dy"],
                "z": cz + atom["dz"],
            })
        molecules.append(atoms)

    meta = {
        "standard_plate_enabled": True,
        "plate_length_x_nm": Lx,
        "plate_width_y_nm": Ly,
        "initial_kerogen_thickness_nm": T,
        "bottom_wall_z_nm": bottom_wall_z,
        "kerogen_z_min_nominal_nm": z_min,
        "kerogen_z_max_nominal_nm": z_max,
        "selected_molecule_count": len(molecules),
        "source_box_nm": source_box[:3],
        "selection_rule": "periodic bulk tiling, whole molecules selected by COM inside fixed x/y/z slab",
    }
    print("STANDARD FIXED-FOOTPRINT KEROGEN SLAB:", json.dumps(meta, ensure_ascii=False))
    return molecules, meta


def main() -> None:
    parser = argparse.ArgumentParser(description="Build fixed-footprint kerogen/graphene pressing cases. Patch v24 supports adding RMS_0p000 without touching existing cases.")
    parser.add_argument("--rms-list", default=None, help="Comma-separated roughness values or case names, e.g. 0.0,0.3 or RMS_0p000")
    parser.add_argument("--preserve-existing", action="store_true", help="Back up/remove only selected target cases instead of all RMS_* cases.")
    args = parser.parse_args()

    cfg = load_config(ROOT)
    if args.rms_list:
        cfg["top_roughness_rms_nm"] = parse_rms_list(args.rms_list)
        print("PATCH V24 SELECTIVE RMS LIST:", cfg["top_roughness_rms_nm"])
    input_dir = ROOT / "00_INPUT"
    bulk_run = ROOT / "01_BULK" / "03_RUN"
    bulk_gro = bulk_run / "bulk_density_0p8_final.gro"
    if not bulk_gro.exists():
        fail(f"Missing densified bulk structure: {bulk_gro}")

    _, atoms, box = read_gro(bulk_gro)
    itp_atoms = read_itp_atoms(input_dir / "kero.itp")
    bonds = read_itp_bonds(input_dir / "kero.itp")
    atoms_per_molecule = len(itp_atoms)
    input_molecule_count = int(cfg["molecule_count"])

    if len(atoms) != atoms_per_molecule * input_molecule_count:
        fail("Bulk GRO atom count does not match molecule_count * atoms_per_molecule.")

    source_molecules = []
    for molecule_index in range(input_molecule_count):
        molecule_atoms = atoms[molecule_index * atoms_per_molecule : (molecule_index + 1) * atoms_per_molecule]
        raw = [(a["x"], a["y"], a["z"]) for a in molecule_atoms]
        unwrapped = unwrap_molecule(raw, bonds, box)
        rebuilt = []
        for atom, coord in zip(molecule_atoms, unwrapped):
            rebuilt.append({"name": atom["atomname"], "x": coord[0], "y": coord[1], "z": coord[2]})
        source_molecules.append(rebuilt)

    kero_molecules, standard_meta = build_periodic_standard_kerogen(source_molecules, box, cfg)
    all_kero = [atom for molecule in kero_molecules for atom in molecule]
    mins = [min(atom[key] for atom in all_kero) for key in ("x", "y", "z")]
    maxs = [max(atom[key] for atom in all_kero) for key in ("x", "y", "z")]
    extents = [maxs[i] - mins[i] for i in range(3)]

    sp = cfg.get("standard_kerogen_plate", {})
    margin = float(cfg["outer_periodic_margin_nm"])
    clearance = float(cfg["wall_clearance_nm"])
    bond_length = float(cfg["graphene_cc_bond_nm"])
    trim = float(cfg["graphene_edge_trim_nm"])
    piston_clearance = float(sp.get("top_piston_side_clearance_nm", 0.05))

    if standard_meta:
        # Patch v15: the final kerogen plate footprint is fixed, but the
        # temporary graphene mold is allowed to be larger.  This avoids the
        # fatal high LJ energy seen in v14 when whole kerogen molecules extend
        # slightly outside the 12 x 12 nm target slab and overlap side/top walls.
        target_x0 = float(sp.get("origin_x_nm", margin))
        target_y0 = float(sp.get("origin_y_nm", margin))
        target_x1 = target_x0 + float(standard_meta["plate_length_x_nm"])
        target_y1 = target_y0 + float(standard_meta["plate_width_y_nm"])

        nominal_bottom_wall_z = float(sp.get("bottom_wall_z_nm", margin))
        bottom_gap = float(sp.get("bottom_wall_to_kerogen_gap_nm", clearance))
        target_thickness = float(standard_meta["initial_kerogen_thickness_nm"])
        target_z_min = nominal_bottom_wall_z + bottom_gap
        target_z_max = target_z_min + target_thickness

        wall_guard_xy = float(sp.get("wall_guard_xy_nm", 2.0))
        wall_atom_clearance = float(sp.get("wall_atom_clearance_nm", max(clearance, 0.60)))

        # Mold walls surround the actual atom extents plus clearance, while the
        # final extracted plate still uses target_x0/target_x1/target_y0/target_y1.
        x0 = min(target_x0 - wall_guard_xy, mins[0] - wall_atom_clearance)
        y0 = min(target_y0 - wall_guard_xy, mins[1] - wall_atom_clearance)
        x1 = max(target_x1 + wall_guard_xy, maxs[0] + wall_atom_clearance)
        y1 = max(target_y1 + wall_guard_xy, maxs[1] + wall_atom_clearance)
        z0 = min(nominal_bottom_wall_z, mins[2] - wall_atom_clearance)

        # Patch v17: never allow the guarded graphene mold to start at a
        # negative coordinate.  Negative wall coordinates are valid in GROMACS,
        # but many visualizers wrap them through PBC, so the left wall appears
        # on the right side.  Translate the whole initial system together; this
        # keeps all distances unchanged and prevents misleading PBC display.
        min_mold_origin = float(sp.get("minimum_mold_origin_nm", margin))
        min_bottom_origin = float(sp.get("minimum_bottom_wall_z_nm", margin))
        shift_x = max(0.0, min_mold_origin - x0)
        shift_y = max(0.0, min_mold_origin - y0)
        shift_z = max(0.0, min_bottom_origin - z0)
        if shift_x or shift_y or shift_z:
            for molecule in kero_molecules:
                for atom in molecule:
                    atom["x"] += shift_x
                    atom["y"] += shift_y
                    atom["z"] += shift_z
            mins = [mins[0] + shift_x, mins[1] + shift_y, mins[2] + shift_z]
            maxs = [maxs[0] + shift_x, maxs[1] + shift_y, maxs[2] + shift_z]
            x0 += shift_x; x1 += shift_x; target_x0 += shift_x; target_x1 += shift_x
            y0 += shift_y; y1 += shift_y; target_y0 += shift_y; target_y1 += shift_y
            z0 += shift_z; target_z_min += shift_z; target_z_max += shift_z

        # Store the shifted fixed extraction window for later output.
        final_target_x0, final_target_x1 = target_x0, target_x1
        final_target_y0, final_target_y1 = target_y0, target_y1

        kero_nominal_max_z = max(target_z_max, maxs[2])
        print("PATCH V17 GUARDED MOLD PULL-COM-SAFE:", json.dumps({
            "target_plate_x_nm": [target_x0, target_x1],
            "target_plate_y_nm": [target_y0, target_y1],
            "mold_wall_x_nm": [x0, x1],
            "mold_wall_y_nm": [y0, y1],
            "bottom_wall_z_nm": z0,
            "actual_kerogen_min_nm": mins,
            "actual_kerogen_max_nm": maxs,
            "wall_atom_clearance_nm": wall_atom_clearance,
            "coordinate_shift_to_avoid_pbc_split_nm": [shift_x, shift_y, shift_z]
        }, ensure_ascii=False))
    else:
        # Fallback legacy geometry.
        x0 = margin
        y0 = margin
        z0 = margin
        x1 = x0 + extents[0] + 2 * clearance
        y1 = y0 + extents[1] + 2 * clearance
        shift = [x0 + clearance - mins[0], y0 + clearance - mins[1], z0 + clearance - mins[2]]
        for molecule in kero_molecules:
            for atom in molecule:
                atom["x"] += shift[0]
                atom["y"] += shift[1]
                atom["z"] += shift[2]
        final_target_x0, final_target_x1 = x0, x1
        final_target_y0, final_target_y1 = y0, y1
        kero_nominal_max_z = z0 + clearance + extents[2]

    top_span_x = (x1 - x0) - 2 * piston_clearance
    top_span_y = (y1 - y0) - 2 * piston_clearance
    top_points, top_bonds, top_angles = honeycomb_patch(top_span_x, top_span_y, trim, bond_length)

    roughness_sets = {}
    global_min = 0.0
    global_max = 0.0
    for rms in cfg["top_roughness_rms_nm"]:
        values = roughness_values(top_points, top_span_x, top_span_y, float(rms), int(cfg["roughness_seed"]))
        roughness_sets[float(rms)] = values
        global_min = min(global_min, min(values))
        global_max = max(global_max, max(values))

    # Keep the lowest valley of the rough piston above the nominal flat kerogen top.
    top_clearance = float(sp.get("initial_top_valley_clearance_nm", clearance))
    top_mean_z = kero_nominal_max_z + top_clearance - global_min
    side_top_z = top_mean_z + global_max + float(sp.get("top_wall_extra_height_nm", 0.35))
    z1 = side_top_z

    # Patch v17: enlarge the simulation box beyond the guarded graphene mold.
    # GROMACS pull COM can become ill-defined when a large pull group spans
    # more than roughly half the periodic box.  The final extracted kerogen
    # plate is still the fixed target window; this extra box space is only
    # vacuum/periodic padding used to keep GTOP/GBOT pull groups inside one
    # image for grompp/mdrun.
    sp_box = cfg.get("standard_kerogen_plate", {})
    extra_xy = float(sp_box.get("pull_com_extra_box_padding_xy_nm", 0.0))
    extra_z = float(sp_box.get("pull_com_extra_box_padding_z_nm", 0.0))
    box_dimensions = [x1 + margin + extra_xy, y1 + margin + extra_xy, z1 + margin + extra_z]

    xy_points, xy_bonds, xy_angles = honeycomb_patch(x1 - x0, y1 - y0, trim, bond_length)
    yz_points, yz_bonds, yz_angles = honeycomb_patch(y1 - y0, z1 - z0, trim, bond_length)
    xz_points, xz_bonds, xz_angles = honeycomb_patch(x1 - x0, z1 - z0, trim, bond_length)

    common_walls = {
        "GBOT": (map_bottom(xy_points, x0, y0, z0), xy_bonds, xy_angles),
        "GXMN": (map_xwall(yz_points, x0, y0, z0), yz_bonds, yz_angles),
        "GXMX": (map_xwall(yz_points, x1, y0, z0), yz_bonds, yz_angles),
        "GYMN": (map_ywall(xz_points, y0, x0, z0), xz_bonds, xz_angles),
        "GYMX": (map_ywall(xz_points, y1, x0, z0), xz_bonds, xz_angles),
    }

    cases_root = ROOT / "02_GRAPHENE_CASES"
    cases_root.mkdir(parents=True, exist_ok=True)
    selected_case_names = [case_name(float(rms)) for rms in cfg["top_roughness_rms_nm"]]
    if args.preserve_existing:
        backup_or_remove_selected_cases(cases_root, selected_case_names, cfg)
    else:
        backup_or_remove_existing_cases(cases_root, cfg)

    molecule_name = read_moleculetype(input_dir / "kero.itp")
    selected_molecule_count = len(kero_molecules)

    for rms in cfg["top_roughness_rms_nm"]:
        rms = float(rms)
        name = case_name(rms)
        case_dir = cases_root / name
        initial_dir = case_dir / "00_INITIAL"
        mdp_dir = case_dir / "01_MDP"
        run_dir = case_dir / "02_RUN"
        initial_dir.mkdir(parents=True)
        mdp_dir.mkdir()
        run_dir.mkdir()

        top_values = roughness_sets[rms]
        top_coords = [
            (x0 + piston_clearance + u, y0 + piston_clearance + v, top_mean_z + top_values[index])
            for index, (u, v) in enumerate(top_points)
        ]

        wall_data = dict(common_walls)
        wall_data["GTOP"] = (top_coords, top_bonds, top_angles)

        for wall_name in WALLS:
            coords, wall_bonds, wall_angles = wall_data[wall_name]
            itp_path = initial_dir / f"{wall_name}.itp"
            write_wall_itp(
                itp_path,
                wall_name,
                coords,
                wall_bonds,
                wall_angles,
                str(cfg["graphene_atom_type"]),
                float(cfg["graphene_bond_k_kj_mol_nm2"]),
                float(cfg["graphene_angle_k_kj_mol_rad2"]),
            )
            if wall_name == "GTOP":
                extra_shape_bonds = inject_gtop_extra_shape_bonds(itp_path, coords, wall_bonds, cfg)
                print(f"{name}: GTOP extra rigid-shape bonds = {extra_shape_bonds}")
            write_wall_shape_lock_files(initial_dir, wall_name, len(coords), cfg)

        shutil.copy2(input_dir / "kero.itp", initial_dir / "kero.itp")
        shutil.copy2(input_dir / "kero_ATP.itp", initial_dir / "kero_ATP.itp")

        molecules = [("kero", molecule) for molecule in kero_molecules]
        for wall_name in WALLS:
            coords = wall_data[wall_name][0]
            molecules.append((wall_name, [{"name": "C", "x": x, "y": y, "z": z} for x, y, z in coords]))

        system_gro = initial_dir / "system_initial.gro"
        write_gro(system_gro, f"Patch v12 fixed-footprint kerogen slab with top RMS {rms:.3f} nm", molecules, box_dimensions)

        write_wall_topology(initial_dir / "topol.top", input_dir / "kero.top", molecule_name, selected_molecule_count, WALLS)

        kero_atom_count = selected_molecule_count * atoms_per_molecule
        groups = {"KERO": list(range(1, kero_atom_count + 1))}
        start = kero_atom_count + 1
        for wall_name in WALLS:
            count = len(wall_data[wall_name][0])
            groups[wall_name] = list(range(start, start + count))
            start += count

        groups["FIXED_WALLS"] = groups["GBOT"] + groups["GXMN"] + groups["GXMX"] + groups["GYMN"] + groups["GYMX"]
        groups["ALL_WALLS"] = groups["GBOT"] + groups["GTOP"] + groups["GXMN"] + groups["GXMX"] + groups["GYMN"] + groups["GYMX"]
        groups["SYSTEM"] = list(range(1, start))
        write_index(initial_dir / "index.ndx", groups)

        _, system_atoms, _ = read_gro(system_gro)
        bottom_atoms = [a for a in system_atoms if a["resname"] == "GBOT"]
        top_atoms = [a for a in system_atoms if a["resname"] == "GTOP"]

        metadata = {
            "case": name,
            "requested_rms_nm": rms,
            "actual_rms_nm": math.sqrt(sum(value * value for value in top_values) / len(top_values)),
            "top_min_shift_nm": min(top_values),
            "top_max_shift_nm": max(top_values),
            "top_mean_z_nm": top_mean_z,
            "top_piston_span_x_nm": top_span_x,
            "top_piston_span_y_nm": top_span_y,
            "projected_top_area_nm2": top_span_x * top_span_y,
            "top_atoms": len(top_coords),
            "bottom_pbcatom": central_atom_number(bottom_atoms),
            "top_pbcatom": central_atom_number(top_atoms),
            "box_nm": box_dimensions,
            "wall_geometry_nm": {
                "x0": x0, "x1": x1, "y0": y0, "y1": y1, "z0": z0, "z1": z1,
                "target_x0": final_target_x0,
                "target_x1": final_target_x1,
                "target_y0": final_target_y0,
                "target_y1": final_target_y1,
                "note": "Patch v17: x0/x1/y0/y1 are temporary guarded mold walls; target_* is the shifted fixed standardized kerogen plate footprint. The whole system is translated if needed so walls do not cross PBC in visualization."
            },
            "standard_kerogen_plate": standard_meta or {},
            "selected_kerogen_molecules": selected_molecule_count,
            "atoms_per_kerogen_molecule": atoms_per_molecule,
            "bulk_source": str(bulk_gro),
        }
        (case_dir / "CASE_METADATA.json").write_text(json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8")

    report = {
        "patch": "v17_fixed_footprint_pull_com_safe_stronger_press",
        "bulk_source": str(bulk_gro),
        "selected_kerogen_molecules": selected_molecule_count,
        "kerogen_extents_nm_after_standard_build": extents,
        "box_nm": box_dimensions,
        "top_mean_z_nm": top_mean_z,
        "global_roughness_min_nm": global_min,
        "global_roughness_max_nm": global_max,
        "standard_kerogen_plate": standard_meta or {},
        "cases": [case_name(float(rms)) for rms in cfg["top_roughness_rms_nm"]],
    }
    (cases_root / "GRAPHENE_BUILD_REPORT.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    print("GRAPHENE CASES COMPLETED: v17 fixed-footprint pull-COM-safe strong-press build.")


if __name__ == "__main__":
    main()
