#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Build an illite mineral substrate under rough kerogen plates.

Inputs expected in project root:
  00_INPUT/Illite*.gro or 00_INPUT/Illite*.pdb
  00_INPUT/Illite*.itp optional but strongly recommended
  02_GRAPHENE_CASES/RMS_xxx/02_RUN/STANDARD_KEROGEN_PLATE/RMS_xxx_standard_kerogen_plate.gro

Outputs:
  ILLITE_UNDER_KEROGEN/RMS_xxx/RMS_xxx_illite_under_kerogen.gro
  ILLITE_UNDER_KEROGEN/RMS_xxx/RMS_xxx_ILLITE_SUPERCELL.itp
  reports and helper files

This is a geometry/topology helper. Always validate force-field parameters before production MD.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import os
import re
import shutil
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np


@dataclass
class Atom:
    resid: int
    resname: str
    atomname: str
    atomnr: int
    x: float
    y: float
    z: float
    vx: Optional[float] = None
    vy: Optional[float] = None
    vz: Optional[float] = None
    element: str = ""
    source_index: Optional[int] = None  # 1-based index in the source template


def fail(msg: str) -> None:
    raise RuntimeError(msg)


def read_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)



def relpath_str(path: Optional[Path], root: Path) -> str:
    if path is None:
        return "NOT_FOUND"
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except Exception:
        return str(path)

def write_json(path: Path, obj: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)


def sanitize_resname(name: str, fallback: str = "MOL") -> str:
    s = re.sub(r"[^A-Za-z0-9]", "", name.strip())
    return (s[:5] or fallback)[:5]


def guess_element(atomname: str) -> str:
    s = re.sub(r"[^A-Za-z]", "", atomname.strip())
    if not s:
        return "X"
    # Common two-letter elements first
    two = s[:2].capitalize()
    one = s[:1].upper()
    known_two = {"Si", "Al", "Mg", "Fe", "Ca", "Na", "Cl", "Li", "Ti", "Mn", "Zn", "Cu", "Ni", "Co", "Cr", "K"}
    if two in known_two:
        return two
    return one


def read_gro(path: Path) -> Tuple[str, List[Atom], np.ndarray]:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    if len(lines) < 3:
        fail(f"Invalid GRO file: {path}")
    title = lines[0].rstrip()
    try:
        n = int(lines[1].strip())
    except Exception as e:
        fail(f"Cannot read atom count in GRO file {path}: {e}")
    atom_lines = lines[2:2+n]
    atoms: List[Atom] = []
    for i, line in enumerate(atom_lines, start=1):
        # Standard GRO fixed columns. Fall back to split when needed.
        try:
            resid = int(line[0:5])
            resname = line[5:10].strip() or "MOL"
            atomname = line[10:15].strip() or "X"
            atomnr = int(line[15:20])
            x = float(line[20:28])
            y = float(line[28:36])
            z = float(line[36:44])
            vx = vy = vz = None
            if len(line) >= 68:
                vx = float(line[44:52])
                vy = float(line[52:60])
                vz = float(line[60:68])
        except Exception:
            parts = line.split()
            if len(parts) < 6:
                fail(f"Cannot parse GRO atom line {i} in {path}: {line}")
            # split format like: 1RES ATOM 1 x y z
            resid_res = parts[0]
            m = re.match(r"^(\d+)(.*)$", resid_res)
            if m:
                resid = int(m.group(1))
                resname = m.group(2) or "MOL"
                atomname = parts[1]
                atomnr = int(parts[2])
                x, y, z = map(float, parts[3:6])
            else:
                resid = int(parts[0]); resname = parts[1]; atomname = parts[2]; atomnr = int(parts[3]); x, y, z = map(float, parts[4:7])
            vx = vy = vz = None
        atoms.append(Atom(resid, resname, atomname, atomnr, x, y, z, vx, vy, vz, guess_element(atomname), i))
    box_line = lines[2+n].split() if len(lines) > 2+n else []
    if len(box_line) >= 3:
        box = np.array([float(box_line[0]), float(box_line[1]), float(box_line[2])], dtype=float)
    else:
        xyz = np.array([[a.x, a.y, a.z] for a in atoms], dtype=float)
        box = xyz.max(axis=0) - xyz.min(axis=0) + 1.0
    return title, atoms, box


def write_gro(path: Path, title: str, atoms: List[Atom], box: Iterable[float]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    box = list(box)
    with path.open("w", encoding="utf-8") as f:
        f.write((title[:200] if title else "Generated by build_illite_under_kerogen.py") + "\n")
        f.write(f"{len(atoms):5d}\n")
        for i, a in enumerate(atoms, start=1):
            resid = int(a.resid) % 100000
            atomnr = i % 100000
            if atomnr == 0:
                atomnr = 99999
            resname = (a.resname or "MOL")[:5]
            atomname = (a.atomname or "X")[:5]
            f.write(f"{resid:5d}{resname:<5}{atomname:>5}{atomnr:5d}{a.x:8.3f}{a.y:8.3f}{a.z:8.3f}\n")
        f.write(f"{box[0]:10.5f}{box[1]:10.5f}{box[2]:10.5f}\n")


def read_pdb(path: Path) -> Tuple[str, List[Atom], np.ndarray]:
    atoms: List[Atom] = []
    box = None
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        rec = line[0:6].strip().upper()
        if rec == "CRYST1":
            try:
                # PDB CRYST1 lengths are Angstrom; convert to nm
                a = float(line[6:15]) / 10.0
                b = float(line[15:24]) / 10.0
                c = float(line[24:33]) / 10.0
                box = np.array([a, b, c], dtype=float)
            except Exception:
                pass
        if rec in {"ATOM", "HETATM"}:
            try:
                atomnr = int(line[6:11])
            except Exception:
                atomnr = len(atoms) + 1
            atomname = line[12:16].strip() or "X"
            resname = line[17:20].strip() or "MOL"
            try:
                resid = int(line[22:26])
            except Exception:
                resid = 1
            try:
                x = float(line[30:38]) / 10.0
                y = float(line[38:46]) / 10.0
                z = float(line[46:54]) / 10.0
            except Exception as e:
                fail(f"Cannot parse PDB coordinate line in {path}: {line}; {e}")
            element = line[76:78].strip() if len(line) >= 78 else guess_element(atomname)
            atoms.append(Atom(resid, sanitize_resname(resname), atomname, atomnr, x, y, z, element=element or guess_element(atomname), source_index=len(atoms)+1))
    if not atoms:
        fail(f"No atoms found in PDB file {path}")
    if box is None:
        xyz = np.array([[a.x, a.y, a.z] for a in atoms], dtype=float)
        box = xyz.max(axis=0) - xyz.min(axis=0) + 1.0
    return path.stem, atoms, box


def load_structure(path: Path) -> Tuple[str, List[Atom], np.ndarray]:
    ext = path.suffix.lower()
    if ext == ".gro":
        return read_gro(path)
    if ext == ".pdb":
        return read_pdb(path)
    fail(f"Unsupported structure file extension: {path}")


def atoms_xyz(atoms: List[Atom]) -> np.ndarray:
    return np.array([[a.x, a.y, a.z] for a in atoms], dtype=float)


def shifted_atoms(atoms: List[Atom], shift: Iterable[float]) -> List[Atom]:
    sx, sy, sz = shift
    return [replace(a, x=a.x + sx, y=a.y + sy, z=a.z + sz) for a in atoms]


def scaled_copy_atom(a: Atom, dx: float, dy: float, dz: float, resid_offset: int = 0) -> Atom:
    return replace(a, resid=a.resid + resid_offset, x=a.x + dx, y=a.y + dy, z=a.z + dz)


def find_file(input_dir: Path, kind: str, explicit: str) -> Optional[Path]:
    if explicit and explicit.lower() != "auto":
        p = Path(explicit)
        if not p.is_absolute():
            p = input_dir / p
        return p if p.exists() else None
    if kind == "structure":
        pats = ["*illite*.gro", "*Illite*.gro", "*ILLITE*.gro", "*illite*.pdb", "*Illite*.pdb", "*ILLITE*.pdb", "*.gro", "*.pdb"]
    else:
        pats = ["*illite*.itp", "*Illite*.itp", "*ILLITE*.itp", "*.itp"]
    for pat in pats:
        hits = sorted([p for p in input_dir.glob(pat) if p.is_file() and not p.name.lower().startswith("posre")])
        if hits:
            return hits[0]
    return None


def parse_itp_atoms(path: Optional[Path]) -> Tuple[Dict[int, dict], Dict[str, dict], List[str]]:
    """Parse [ atoms ] from an ITP. Return by index and by atomname maps.

    GROMACS atom line usually:
      nr type resnr residue atom cgnr charge mass
    """
    by_index: Dict[int, dict] = {}
    by_name: Dict[str, dict] = {}
    raw_lines: List[str] = []
    if path is None or not path.exists():
        return by_index, by_name, raw_lines
    in_atoms = False
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        raw_lines.append(raw)
        line = raw.split(";", 1)[0].strip()
        if not line:
            continue
        if line.startswith("[") and line.endswith("]"):
            sec = line.strip("[]").strip().lower()
            in_atoms = (sec == "atoms")
            continue
        if not in_atoms:
            continue
        parts = line.split()
        if len(parts) < 7:
            continue
        try:
            nr = int(parts[0])
            atype = parts[1]
            resnr = int(parts[2]) if parts[2].lstrip("-").isdigit() else 1
            resid = parts[3]
            atom = parts[4]
            cgnr = int(parts[5]) if parts[5].lstrip("-").isdigit() else nr
            charge = float(parts[6])
            mass = float(parts[7]) if len(parts) > 7 else None
        except Exception:
            continue
        rec = {"type": atype, "resnr": resnr, "resid": resid, "atom": atom, "cgnr": cgnr, "charge": charge, "mass": mass}
        by_index[nr] = rec
        by_name.setdefault(atom, rec)
    return by_index, by_name, raw_lines


def surface_grid(atoms: List[Atom], side: str, dx: float, dy: float) -> Tuple[np.ndarray, dict]:
    xyz = atoms_xyz(atoms)
    if xyz.size == 0:
        return np.empty((0, 3)), {}
    xmin, ymin = xyz[:, 0].min(), xyz[:, 1].min()
    xmax, ymax = xyz[:, 0].max(), xyz[:, 1].max()
    nx = max(1, int(math.ceil((xmax - xmin) / dx)))
    ny = max(1, int(math.ceil((ymax - ymin) / dy)))
    grid = {}
    for x, y, z in xyz:
        ix = min(nx - 1, max(0, int((x - xmin) / dx)))
        iy = min(ny - 1, max(0, int((y - ymin) / dy)))
        key = (ix, iy)
        if key not in grid:
            grid[key] = [x, y, z]
        else:
            if side == "top" and z > grid[key][2]:
                grid[key] = [x, y, z]
            elif side == "bottom" and z < grid[key][2]:
                grid[key] = [x, y, z]
    pts = np.array(list(grid.values()), dtype=float)
    meta = {"nx": nx, "ny": ny, "coverage": len(grid) / float(nx * ny), "xmin": xmin, "xmax": xmax, "ymin": ymin, "ymax": ymax}
    return pts, meta


def roughness_metrics(points: np.ndarray) -> dict:
    if points.size == 0:
        return {"rms_nm": float("nan"), "ptv_nm": float("nan"), "mean_z_nm": float("nan")}
    z = points[:, 2]
    return {
        "rms_nm": float(np.sqrt(np.mean((z - np.mean(z)) ** 2))),
        "ptv_nm": float(np.max(z) - np.min(z)),
        "mean_z_nm": float(np.mean(z)),
    }


def orient_kerogen_rough_top(atoms: List[Atom], box: np.ndarray, cfg: dict) -> Tuple[List[Atom], bool, dict]:
    dx = float(cfg.get("roughness_grid_dx_nm", 0.25))
    dy = float(cfg.get("roughness_grid_dy_nm", 0.25))
    top_pts, top_meta = surface_grid(atoms, "top", dx, dy)
    bot_pts, bot_meta = surface_grid(atoms, "bottom", dx, dy)
    top_m = roughness_metrics(top_pts)
    bot_m = roughness_metrics(bot_pts)
    flipped = False
    oriented = atoms
    if bool(cfg.get("auto_flip_kerogen_rough_top", True)):
        # Flip when bottom is substantially rougher than top.
        if np.isfinite(bot_m["rms_nm"]) and np.isfinite(top_m["rms_nm"]) and bot_m["rms_nm"] > top_m["rms_nm"] * 1.10:
            zmin = atoms_xyz(atoms)[:, 2].min()
            zmax = atoms_xyz(atoms)[:, 2].max()
            oriented = [replace(a, z=(zmin + zmax - a.z)) for a in atoms]
            flipped = True
    report = {
        "kerogen_top_rms_before_nm": top_m["rms_nm"],
        "kerogen_bottom_rms_before_nm": bot_m["rms_nm"],
        "flipped_z": flipped,
        "kerogen_top_grid_coverage": top_meta.get("coverage", float("nan")),
        "kerogen_bottom_grid_coverage": bot_meta.get("coverage", float("nan")),
    }
    return oriented, flipped, report


def center_kerogen_to_nominal_plate(atoms: List[Atom], Lx: float, Ly: float) -> List[Atom]:
    xyz = atoms_xyz(atoms)
    cx = 0.5 * (xyz[:, 0].min() + xyz[:, 0].max())
    cy = 0.5 * (xyz[:, 1].min() + xyz[:, 1].max())
    return shifted_atoms(atoms, [Lx / 2.0 - cx, Ly / 2.0 - cy, 0.0])




def _is_auto_value(v) -> bool:
    return v is None or (isinstance(v, str) and v.strip().lower() in {"auto", "from_kerogen", "global", "per_case"})


def round_up(value: float, step: float) -> float:
    if step <= 0:
        return float(value)
    return float(math.ceil(float(value) / step) * step)


def measure_kerogen_xy_footprint(atoms: List[Atom], cfg: dict) -> dict:
    """Measure the actual x/y footprint of a kerogen plate from atom coordinates.

    The default uses 0--100 percentile, i.e. true min/max atom extents.
    To ignore rare dangling atoms, set kerogen_xy_measure_percentile_low/high,
    for example 0.5 and 99.5.
    """
    xyz = atoms_xyz(atoms)
    plow = float(cfg.get("kerogen_xy_measure_percentile_low", 0.0))
    phigh = float(cfg.get("kerogen_xy_measure_percentile_high", 100.0))
    xmin = float(np.percentile(xyz[:, 0], plow))
    xmax = float(np.percentile(xyz[:, 0], phigh))
    ymin = float(np.percentile(xyz[:, 1], plow))
    ymax = float(np.percentile(xyz[:, 1], phigh))
    return {
        "measured_xmin_nm": xmin,
        "measured_xmax_nm": xmax,
        "measured_ymin_nm": ymin,
        "measured_ymax_nm": ymax,
        "measured_length_x_nm": xmax - xmin,
        "measured_width_y_nm": ymax - ymin,
        "measure_percentile_low": plow,
        "measure_percentile_high": phigh,
    }


def resolve_target_xy_for_cases(preloaded: Dict[str, dict], cfg: dict) -> Dict[str, Tuple[float, float]]:
    """Resolve target Lx/Ly for illite replication.

    target_xy_mode:
      fixed: use target_plate_length_x_nm and target_plate_width_y_nm.
      per_case_from_kerogen: each case uses its own measured kerogen footprint.
      global_max_from_kerogen: all cases use the max measured footprint across cases.

    global_max_from_kerogen is recommended for comparing roughness cases because
    all illite substrates will have the same x/y size, but that size is read
    from the actual kerogen plates rather than hard-coded as 12x12 nm.
    """
    mode = str(cfg.get("target_xy_mode", "global_max_from_kerogen")).strip().lower()
    padding = float(cfg.get("kerogen_xy_padding_nm", 0.20))
    step = float(cfg.get("xy_round_up_nm", 0.05))
    raw_lx = cfg.get("target_plate_length_x_nm", "auto")
    raw_ly = cfg.get("target_plate_width_y_nm", "auto")

    if mode == "fixed" or (not _is_auto_value(raw_lx) and not _is_auto_value(raw_ly)):
        Lx = float(raw_lx)
        Ly = float(raw_ly)
        return {case: (Lx, Ly) for case in preloaded}

    measured = {}
    for case, rec in preloaded.items():
        m = rec["xy_measure"]
        lx = round_up(float(m["measured_length_x_nm"]) + 2.0 * padding, step)
        ly = round_up(float(m["measured_width_y_nm"]) + 2.0 * padding, step)
        measured[case] = (lx, ly)

    if mode in {"per_case", "per_case_from_kerogen", "case"}:
        return measured

    # Default: same dimensions for all roughness cases, determined from the largest kerogen plate.
    gx = max(v[0] for v in measured.values())
    gy = max(v[1] for v in measured.values())
    return {case: (gx, gy) for case in preloaded}

def replicate_and_crop_illite(template_atoms: List[Atom], template_box: np.ndarray, cfg: dict, Lx: float, Ly: float, thickness: float) -> Tuple[List[Atom], dict]:
    xyz = atoms_xyz(template_atoms)
    # Shift template to start at zero; use box vectors if available, otherwise extents.
    mins = xyz.min(axis=0)
    base_atoms = shifted_atoms(template_atoms, -mins)
    base_xyz = atoms_xyz(base_atoms)
    ext = base_xyz.max(axis=0) - base_xyz.min(axis=0)
    cell = np.array(template_box, dtype=float)
    for i in range(3):
        if cell[i] <= 0.05 or cell[i] < ext[i] * 0.7:
            cell[i] = max(ext[i], 0.1)
    margin = float(cfg.get("xy_margin_nm", 0.2))
    target_x = Lx + 2 * margin
    target_y = Ly + 2 * margin
    target_z = thickness
    nx = max(1, int(math.ceil(target_x / cell[0])) + 1)
    ny = max(1, int(math.ceil(target_y / cell[1])) + 1)
    nz = max(1, int(math.ceil(target_z / cell[2])) + 1)
    replicated: List[Atom] = []
    resid_offset = 0
    for ix in range(nx):
        for iy in range(ny):
            for iz in range(nz):
                dx = ix * cell[0]
                dy = iy * cell[1]
                dz = iz * cell[2]
                for a in base_atoms:
                    replicated.append(scaled_copy_atom(a, dx, dy, dz, resid_offset=resid_offset))
                resid_offset += max(1, max(a.resid for a in base_atoms))
    # Center supercell footprint around nominal plate, then crop.
    rep_xyz = atoms_xyz(replicated)
    rep_min = rep_xyz.min(axis=0)
    rep_max = rep_xyz.max(axis=0)
    shift = np.array([-(rep_min[0]) + (-margin), -(rep_min[1]) + (-margin), -(rep_min[2])], dtype=float)
    replicated = shifted_atoms(replicated, shift)
    cropped: List[Atom] = []
    crop_xy = bool(cfg.get("crop_illite_to_nominal_xy", True))
    for a in replicated:
        in_z = 0.0 <= a.z <= thickness + 1e-6
        if crop_xy:
            in_xy = (-margin <= a.x <= Lx + margin) and (-margin <= a.y <= Ly + margin)
        else:
            in_xy = True
        if in_xy and in_z:
            cropped.append(a)
    if not cropped:
        fail("Illite replication/cropping produced zero atoms. Check template box and target dimensions.")
    # Rename resname to consistent ILL.
    resname = str(cfg.get("illite_resname", "ILL"))[:5]
    cropped = [replace(a, resname=resname, resid=1 + (i // max(1, len(base_atoms)))) for i, a in enumerate(cropped)]
    report = {
        "illite_template_cell_x_nm": float(cell[0]),
        "illite_template_cell_y_nm": float(cell[1]),
        "illite_template_cell_z_nm": float(cell[2]),
        "illite_replicate_nx": nx,
        "illite_replicate_ny": ny,
        "illite_replicate_nz": nz,
        "illite_atoms_after_crop": len(cropped),
    }
    return cropped, report


def infer_illite_thickness(kerogen_atoms: List[Atom], cfg: dict) -> float:
    mode = str(cfg.get("illite_thickness_mode", "fixed")).lower()
    if mode == "fixed":
        return float(cfg.get("illite_thickness_nm", 2.5))
    xyz = atoms_xyz(kerogen_atoms)
    k_thick = float(np.percentile(xyz[:, 2], 95) - np.percentile(xyz[:, 2], 5))
    if mode in {"match", "match_kerogen"}:
        return max(1.0, k_thick)
    if mode.startswith("fraction") or mode.startswith("match_kerogen_fraction"):
        frac = float(cfg.get("illite_thickness_fraction_of_kerogen", 0.35))
        return max(1.0, k_thick * frac)
    return float(cfg.get("illite_thickness_nm", 2.5))


def place_illite_below_kerogen(illite_atoms: List[Atom], kerogen_atoms: List[Atom], cfg: dict) -> Tuple[List[Atom], List[Atom], np.ndarray, dict]:
    Lx = float(cfg.get("target_plate_length_x_nm", 12.0))
    Ly = float(cfg.get("target_plate_width_y_nm", 12.0))
    gap = float(cfg.get("gap_between_illite_top_and_kerogen_bottom_nm", 0.25))
    # Kerogen bottom reference as 5th percentile: robust to dangling atoms.
    kxyz = atoms_xyz(kerogen_atoms)
    k_bottom_ref = float(np.percentile(kxyz[:, 2], float(cfg.get("surface_percentile_bottom", 5.0))))
    k_top_ref = float(np.percentile(kxyz[:, 2], float(cfg.get("surface_percentile_top", 95.0))))
    ixyz = atoms_xyz(illite_atoms)
    i_top = float(ixyz[:, 2].max())
    dz = (k_bottom_ref - gap) - i_top
    illite_placed = shifted_atoms(illite_atoms, [0.0, 0.0, dz])
    all_xyz = np.vstack([atoms_xyz(illite_placed), kxyz])
    zmin = float(all_xyz[:, 2].min())
    zmax = float(all_xyz[:, 2].max())
    bottom_pad = float(cfg.get("box_z_padding_bottom_nm", 1.0))
    top_pad = float(cfg.get("box_z_padding_top_nm", 3.0))
    # Shift everything upward to leave bottom padding and non-negative coords.
    global_shift = np.array([float(cfg.get("box_xy_padding_nm", 2.0)), float(cfg.get("box_xy_padding_nm", 2.0)), bottom_pad - zmin])
    kerogen_shifted = shifted_atoms(kerogen_atoms, global_shift)
    illite_shifted = shifted_atoms(illite_placed, global_shift)
    box_x = Lx + 2 * float(cfg.get("box_xy_padding_nm", 2.0))
    box_y = Ly + 2 * float(cfg.get("box_xy_padding_nm", 2.0))
    new_xyz = np.vstack([atoms_xyz(illite_shifted), atoms_xyz(kerogen_shifted)])
    box_z = float(new_xyz[:, 2].max() + top_pad)
    report = {
        "kerogen_bottom_ref_p5_nm_before_shift": k_bottom_ref,
        "kerogen_top_ref_p95_nm_before_shift": k_top_ref,
        "gap_between_illite_top_and_kerogen_bottom_ref_nm": gap,
        "global_shift_x_nm": float(global_shift[0]),
        "global_shift_y_nm": float(global_shift[1]),
        "global_shift_z_nm": float(global_shift[2]),
        "box_x_nm": box_x,
        "box_y_nm": box_y,
        "box_z_nm": box_z,
    }
    return illite_shifted, kerogen_shifted, np.array([box_x, box_y, box_z], dtype=float), report


def make_pbc_view(atoms: List[Atom], box: np.ndarray, nx: int = 3, ny: int = 3) -> List[Atom]:
    out: List[Atom] = []
    # Center 3x3 around original cell.
    for ix in range(-(nx // 2), nx // 2 + 1):
        for iy in range(-(ny // 2), ny // 2 + 1):
            for a in atoms:
                out.append(replace(a, x=a.x + ix * box[0], y=a.y + iy * box[1]))
    return out


def write_illite_itp(path: Path, posre_path: Path, illite_atoms: List[Atom], template_map_idx: Dict[int, dict], template_map_name: Dict[str, dict], cfg: dict) -> dict:
    path.parent.mkdir(parents=True, exist_ok=True)
    molname = str(cfg.get("illite_moleculetype_name", "ILLITE"))
    resname = str(cfg.get("illite_resname", "ILL"))[:5]
    fallback_charge = float(cfg.get("fallback_charge", 0.0))
    fallback_mass = float(cfg.get("fallback_mass", 28.0855))
    total_charge = 0.0
    missing = 0
    with path.open("w", encoding="utf-8") as f:
        f.write("; Generated by build_illite_under_kerogen.py\n")
        f.write("; Check atom types, charges and force-field includes before production MD.\n\n")
        f.write("[ moleculetype ]\n")
        f.write(f"; name  nrexcl\n{molname:<16s} 1\n\n")
        f.write("[ atoms ]\n")
        f.write("; nr  type  resnr  residue  atom  cgnr  charge  mass\n")
        for i, a in enumerate(illite_atoms, start=1):
            rec = template_map_idx.get(a.source_index or -1) or template_map_name.get(a.atomname)
            if rec:
                atype = rec["type"]
                charge = float(rec.get("charge", fallback_charge))
                mass = rec.get("mass")
                if mass is None:
                    mass = fallback_mass
            else:
                atype = a.atomname
                charge = fallback_charge
                mass = fallback_mass
                missing += 1
            total_charge += charge
            atom = (a.atomname or atype)[:6]
            f.write(f"{i:6d} {atype:<10s} {1:6d} {resname:<6s} {atom:<6s} {i:6d} {charge:12.6f} {float(mass):10.4f}\n")
        f.write("\n#ifdef POSRES_ILLITE\n")
        f.write(f"#include \"{posre_path.name}\"\n")
        f.write("#endif\n")
    k = float(cfg.get("position_restraint_k_kj_mol_nm2", 1000000.0))
    with posre_path.open("w", encoding="utf-8") as f:
        f.write("; Position restraints for generated illite supercell\n")
        f.write("[ position_restraints ]\n")
        f.write("; atom  type  fx  fy  fz\n")
        for i in range(1, len(illite_atoms) + 1):
            f.write(f"{i:6d} 1 {k:12.1f} {k:12.1f} {k:12.1f}\n")
    return {"illite_total_charge_from_generated_itp_e": total_charge, "illite_atoms_missing_type_or_charge": missing}


def write_topol_template(path: Path, case: str, itp_name: str, cfg: dict) -> None:
    molname = str(cfg.get("illite_moleculetype_name", "ILLITE"))
    with path.open("w", encoding="utf-8") as f:
        f.write("; Template topology for kerogen + illite composite.\n")
        f.write("; You must merge this with your actual kerogen/fluid force-field topology before production MD.\n")
        f.write("; Put downloaded force-field includes before molecule itp files as required by HZW/CLAYFF/INTERFACE.\n\n")
        f.write("; Example:\n")
        f.write("; #include \"forcefield.itp\"\n")
        f.write("; #include \"kerogen.itp\"\n")
        f.write(f"#include \"{itp_name}\"\n\n")
        f.write("[ system ]\n")
        f.write(f"Kerogen rough plate on illite substrate - {case}\n\n")
        f.write("[ molecules ]\n")
        f.write(f"; KERO    <fill with your kerogen molecule count>\n")
        f.write(f"{molname:<16s} 1\n")


def copy_input_forcefield_files(input_dir: Path, out_dir: Path) -> None:
    ff_dir = out_dir / "00_INPUT_FORCEFIELD_COPY"
    ff_dir.mkdir(parents=True, exist_ok=True)
    for p in input_dir.iterdir():
        if p.is_file() and p.suffix.lower() in {".itp", ".top", ".rtp", ".atp", ".nb", ".prm", ".ff", ".dat"}:
            try:
                shutil.copy2(p, ff_dir / p.name)
            except Exception:
                pass


def write_case_report(path: Path, report: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        w = csv.DictWriter(f, fieldnames=list(report.keys()))
        w.writeheader()
        w.writerow(report)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="illite_under_kerogen_config.json")
    args = ap.parse_args()

    root = Path.cwd()
    cfg_path = root / args.config
    cfg = read_json(cfg_path)
    input_dir = root / cfg.get("input_dir", "00_INPUT")
    if not input_dir.exists():
        fail(f"Input directory not found: {input_dir}. Put downloaded Illite files in 00_INPUT.")

    illite_structure = find_file(input_dir, "structure", str(cfg.get("illite_structure_file", "auto")))
    if illite_structure is None:
        fail(f"No Illite .gro/.pdb found in {input_dir}")
    illite_itp = find_file(input_dir, "itp", str(cfg.get("illite_itp_file", "auto")))

    title, illite_template_atoms, illite_template_box = load_structure(illite_structure)
    itp_by_idx, itp_by_name, _ = parse_itp_atoms(illite_itp)

    out_root = root / cfg.get("output_dir", "ILLITE_UNDER_KEROGEN")
    out_root.mkdir(parents=True, exist_ok=True)
    copy_input_forcefield_files(input_dir, out_root)

    all_reports: List[dict] = []

    # First pass: read all kerogen plates and measure their actual x/y footprint.
    # This lets the illite slab size follow the real kerogen dimensions instead of a hard-coded 12x12 nm.
    preloaded: Dict[str, dict] = {}
    for case in cfg.get("cases", ["RMS_0p300", "RMS_0p600", "RMS_0p900"]):
        kerogen_path = root / str(cfg.get("kerogen_plate_pattern")).format(case=case)
        if not kerogen_path.exists():
            print(f"WARNING: missing kerogen plate for {case}: {kerogen_path}. Skipped.")
            continue
        _, kerogen_atoms_raw, kerogen_box = load_structure(kerogen_path)
        kerogen_atoms, flipped, orient_report = orient_kerogen_rough_top(kerogen_atoms_raw, kerogen_box, cfg)
        xy_measure = measure_kerogen_xy_footprint(kerogen_atoms, cfg)
        preloaded[case] = {
            "kerogen_path": kerogen_path,
            "kerogen_box": kerogen_box,
            "kerogen_atoms": kerogen_atoms,
            "flipped": flipped,
            "orient_report": orient_report,
            "xy_measure": xy_measure,
        }

    if not preloaded:
        fail("No kerogen plates were found. Check kerogen_plate_pattern and cases in config.")

    target_xy = resolve_target_xy_for_cases(preloaded, cfg)
    print("ILLITE TARGET XY FROM KEROGEN:", json.dumps({k: {"Lx_nm": v[0], "Ly_nm": v[1], **preloaded[k]["xy_measure"]} for k, v in target_xy.items()}, ensure_ascii=False))

    for case, rec in preloaded.items():
        kerogen_path = rec["kerogen_path"]
        kerogen_box = rec["kerogen_box"]
        kerogen_atoms = rec["kerogen_atoms"]
        flipped = rec["flipped"]
        orient_report = rec["orient_report"]
        xy_measure = rec["xy_measure"]
        Lx, Ly = target_xy[case]
        if bool(cfg.get("center_nominal_plate_in_box", True)):
            kerogen_atoms = center_kerogen_to_nominal_plate(kerogen_atoms, Lx, Ly)

        illite_thick = infer_illite_thickness(kerogen_atoms, cfg)
        illite_super, rep_report = replicate_and_crop_illite(illite_template_atoms, illite_template_box, cfg, Lx, Ly, illite_thick)
        illite_placed, kerogen_placed, box, place_report = place_illite_below_kerogen(illite_super, kerogen_atoms, cfg)

        out_dir = out_root / case
        out_dir.mkdir(parents=True, exist_ok=True)
        combined = illite_placed + kerogen_placed
        # Renumber residues/atoms for visualization.
        illite_final = [replace(a, resid=1) for a in illite_placed]
        kerogen_final = [replace(a, resid=a.resid + 1000) for a in kerogen_placed]
        combined = illite_final + kerogen_final

        write_gro(out_dir / f"{case}_illite_only.gro", f"{case} generated illite substrate only", illite_final, box)
        write_gro(out_dir / f"{case}_kerogen_oriented_rough_top.gro", f"{case} kerogen oriented rough top", kerogen_final, box)
        write_gro(out_dir / f"{case}_illite_under_kerogen.gro", f"{case} illite under rough kerogen", combined, box)
        if bool(cfg.get("write_pbc_view_3x3", True)):
            pbc_atoms = make_pbc_view(combined, box, 3, 3)
            pbc_box = np.array([box[0] * 3, box[1] * 3, box[2]], dtype=float)
            # Shift to positive display box
            xyzp = atoms_xyz(pbc_atoms)
            pbc_atoms = shifted_atoms(pbc_atoms, -xyzp.min(axis=0) + np.array([0.2, 0.2, 0.0]))
            write_gro(out_dir / f"{case}_illite_under_kerogen_PBC_VIEW_3x3.gro", f"{case} 3x3 PBC view only", pbc_atoms, pbc_box)

        itp_report = {}
        if bool(cfg.get("write_gromacs_itp", True)):
            itp_path = out_dir / f"{case}_ILLITE_SUPERCELL.itp"
            posre_path = out_dir / f"{case}_posre_illite.itp"
            itp_report = write_illite_itp(itp_path, posre_path, illite_final, itp_by_idx, itp_by_name, cfg)
            write_topol_template(out_dir / f"{case}_composite_topol_template.top", case, itp_path.name, cfg)

        kxyz = atoms_xyz(kerogen_final)
        ixyz = atoms_xyz(illite_final)
        top_pts, top_meta = surface_grid(kerogen_final, "top", float(cfg.get("roughness_grid_dx_nm", 0.25)), float(cfg.get("roughness_grid_dy_nm", 0.25)))
        top_m = roughness_metrics(top_pts)
        report = {
            "case": case,
            "illite_structure_file": relpath_str(illite_structure, root),
            "illite_itp_file": relpath_str(illite_itp, root),
            "target_plate_length_x_nm": Lx,
            "target_plate_width_y_nm": Ly,
            "target_xy_mode": str(cfg.get("target_xy_mode", "global_max_from_kerogen")),
            "kerogen_measured_length_x_nm": xy_measure["measured_length_x_nm"],
            "kerogen_measured_width_y_nm": xy_measure["measured_width_y_nm"],
            "kerogen_measured_xmin_nm": xy_measure["measured_xmin_nm"],
            "kerogen_measured_xmax_nm": xy_measure["measured_xmax_nm"],
            "kerogen_measured_ymin_nm": xy_measure["measured_ymin_nm"],
            "kerogen_measured_ymax_nm": xy_measure["measured_ymax_nm"],
            "kerogen_input_file": str(kerogen_path.relative_to(root)),
            "kerogen_atoms": len(kerogen_final),
            "kerogen_min_x_nm": float(kxyz[:, 0].min()),
            "kerogen_max_x_nm": float(kxyz[:, 0].max()),
            "kerogen_min_y_nm": float(kxyz[:, 1].min()),
            "kerogen_max_y_nm": float(kxyz[:, 1].max()),
            "kerogen_min_z_nm": float(kxyz[:, 2].min()),
            "kerogen_max_z_nm": float(kxyz[:, 2].max()),
            "kerogen_thickness_p95_p05_nm": float(np.percentile(kxyz[:, 2], 95) - np.percentile(kxyz[:, 2], 5)),
            "kerogen_top_rms_nm": top_m["rms_nm"],
            "kerogen_top_peak_to_valley_nm": top_m["ptv_nm"],
            "kerogen_top_grid_coverage": top_meta.get("coverage", float("nan")),
            "flipped_z_to_make_rough_top": flipped,
            "illite_atoms": len(illite_final),
            "illite_min_x_nm": float(ixyz[:, 0].min()),
            "illite_max_x_nm": float(ixyz[:, 0].max()),
            "illite_min_y_nm": float(ixyz[:, 1].min()),
            "illite_max_y_nm": float(ixyz[:, 1].max()),
            "illite_min_z_nm": float(ixyz[:, 2].min()),
            "illite_max_z_nm": float(ixyz[:, 2].max()),
            "illite_thickness_nm": float(ixyz[:, 2].max() - ixyz[:, 2].min()),
            "box_x_nm": float(box[0]),
            "box_y_nm": float(box[1]),
            "box_z_nm": float(box[2]),
            **orient_report,
            **rep_report,
            **place_report,
            **itp_report,
        }
        write_case_report(out_dir / f"{case}_build_report.csv", report)
        write_json(out_dir / f"{case}_build_report.json", report)
        all_reports.append(report)
        print(f"BUILT {case}: illite atoms={len(illite_final)}, kerogen atoms={len(kerogen_final)}, output={out_dir}")

    if all_reports:
        all_keys = []
        for r in all_reports:
            for k in r.keys():
                if k not in all_keys:
                    all_keys.append(k)
        with (out_root / "ILLITE_BUILD_REPORT_ALL.csv").open("w", newline="", encoding="utf-8-sig") as f:
            w = csv.DictWriter(f, fieldnames=all_keys)
            w.writeheader()
            for r in all_reports:
                w.writerow(r)
        write_json(out_root / "ILLITE_BUILD_REPORT_ALL.json", {"reports": all_reports})
    else:
        fail("No cases were built. Check kerogen plate files and config cases.")

    print("ALL DONE. Summary:", out_root / "ILLITE_BUILD_REPORT_ALL.csv")


if __name__ == "__main__":
    main()
